language: python
manifest file: pyproject.toml

commit message: 🔖 Release {new}
tag name: v{new}

milestone title: "{new}"
release title: "{new}"
release assets:
  - label: Python wheel
    file: dist/{package}-{new}-py3-none-any.whl

  - label: Source code tarball
    file: dist/{package}-{new}.tar.gz

version declarations:
  - in: ./{package}/__init__.py
    search: ^__version__ = "(.+)"$
    replace: __version__ = "{new}"

steps:
  bump manifest version: poetry version {bump}
  build for registry: poetry build
  publish to registry: poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD
