language: python
python:
  - '3.8'

before_install:
  - touch .env
  - echo -ne "SECRET_KEY=\"$SECRET_KEY\"\n" >> .env
  - echo -ne "ARANGODB_USERNAME=\"root\"\n" >> .env
  - echo -ne "ARANGODB_PASSWORD=\"root\"\n" >> .env
  - pip install 'poetry>=1.0'
  - echo arangodb3 arangodb/password password root | sudo debconf-set-selections  # set username 'root'
  - echo arangodb3 arangodb/password_again password root | sudo debconf-set-selections  # set password 'root'
  - chmod +x setup_ci_arangodb.sh
  - ./setup_ci_arangodb.sh

install:
  - poetry install

script:
  - make test
