language: python
python:
  - '3.7'

before_install:
  - touch .env
  - echo -ne "SECRET_KEY=\"$SECRET_KEY\"\n" >> .env
  - pip install 'poetry>=1.0'

install:
  - poetry install

script:
  - make test
