language: python
python:
  - '3.8'
services:
  - docker

before_install:
  - touch .env
  - echo -ne "SECRET_KEY=\"$SECRET_KEY\"\n" >> .env
  - echo -ne "ARANGODB_USERNAME=\"root\"\n" >> .env
  - echo -ne "ARANGO_ROOT_PASSWORD=\"openSesame\"\n" >> .env
  - echo -ne "GITHUB_USERNAME=\"$GITHUB_USERNAME\"\n" >> .env
  - echo -ne "GITHUB_TOKEN=\"$GITHUB_TOKEN\"\n" >> .env
  - pip install 'poetry>=1.0'
  - docker run -d -p 8529:8529 -e ARANGO_ROOT_PASSWORD=openSesame arangodb/arangodb:3.6.5

install:
  - poetry install

script:
  - ls /home/travis/.cache/pypoetry/virtualenvs/
  - make test

after_success:
  - poetry run codecov
