default_context:
  project_name: 'Schoolsyst API'
  project_slug: 'schoolsyst-api'
  domain_main: 'api.schoolsyst.com'
  domain_staging: 'stag.api.schoolsyst.com'
  docker_swarm_stack_name_main: 'api-schoolsyst-com'
  docker_swarm_stack_name_staging: 'stag-api-schoolsyst-com'
  secret_key: 'd654ccbf0bc528976fcac45fc84685abb582db6d450345182b4210eebe84550a'
  first_superuser: 'admin@api.schoolsyst.com'
  first_superuser_password: 'buckshot-glorify4-shrine-fiscally-stainless-opal'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.api.schoolsyst.com", "https://stag.api.schoolsyst.com", "https://api.schoolsyst.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@api.schoolsyst.com'
  postgres_password: '5ca5f0c7c98df2a14f324534dbcc1ca054a8710609749ca01e09776cf43a85b3'
  pgadmin_default_user: 'admin@api.schoolsyst.com'
  pgadmin_default_user_password: 'armband-much-profane5-sporting-starless-greeter'
  traefik_constraint_tag: 'api.schoolsyst.com'
  traefik_constraint_tag_staging: 'stag.api.schoolsyst.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:buckshot-glorify4-shrine-fiscally-stainless-opal'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
